const express = require('express');
const router = express.Router();
const multer = require('multer');
const path = require('path');
const Provider = require('../models/Provider');
const { protect } = require('../middleware/authMiddleware');

// 1. Configure Storage Engine
const storage = multer.diskStorage({
  destination: './uploads/', 
  filename: (req, file, cb) => {
    cb(null, `${Date.now()}-${file.originalname}`);
  }
});

const upload = multer({ 
  storage: storage,
  limits: { fileSize: 5000000 }, 
});

/**
 * 2. GET ALL PROVIDERS (Explore Page)
 */
router.get('/', async (req, res) => {
  try {
    const providers = await Provider.find().sort({ createdAt: -1 });
    res.json(providers);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/**
 * 3. GET USER WORKSPACE (Dashboard)
 * MUST stay above the '/:id' route.
 */
router.get('/my-workspace', protect, async (req, res) => {
  try {
    const niches = await Provider.find({ ownerId: req.user.uid }).sort({ createdAt: -1 });
    res.json(niches);
  } catch (err) {
    res.status(500).json({ error: "Failed to load workspace" });
  }
});

/**
 * 4. GET SINGLE PROVIDER BY ID (Profile Page)
 */
router.get('/:id', async (req, res) => {
  try {
    const provider = await Provider.findById(req.params.id);
    if (!provider) return res.status(404).json({ message: "Niche not found" });
    res.json(provider);
  } catch (err) {
    res.status(500).json({ error: "Invalid ID format" });
  }
});

/**
 * 5. REGISTER NEW NICHE (With Local Image)
 */
router.post('/', protect, upload.single('logo'), async (req, res) => {
  try {
    const { businessName, category, targetCustomer, desiredService, website } = req.body;
    
    // Use the file path generated by Multer
   // Change your logoUrl line to this:
const logoUrl = req.file ? `${req.protocol}://${req.get('host')}/uploads/${req.file.filename}` : "";
    const newProvider = new Provider({
      businessName,
      category,
      targetCustomer,
      desiredService,
      website,
      logoUrl,
      ownerId: req.user.uid,
      reviews: [],
      activeUsers: []
    });

    const saved = await newProvider.save();
    res.status(201).json(saved);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

/**
 * 6. POST A REVIEW
 */
router.post('/:id/reviews', protect, async (req, res) => {
  try {
    const { rating, comment } = req.body;
    const provider = await Provider.findById(req.params.id);
    if (!provider) return res.status(404).json({ message: "Niche not found" });

    const newReview = {
      userId: req.user.uid,
      userName: req.user.name || "Verified Member",
      rating: Number(rating),
      comment,
      createdAt: new Date()
    };

    provider.reviews.push(newReview);
    await provider.save();
    res.status(201).json(provider.reviews);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;